theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlp4s0"
format = "wlp4s0: {ip} {speed_down} {speed_up}"

[[block]]
block = "net"
device = "wg0"
format = "wg0: {ip} {speed_down} {speed_up}"

[[block]]
block = "net"
device = "tun0"
format = "tun0: {ip} {speed_down} {speed_up}"

[[block]]
block = "battery"
device = "BAT1"
format = "{percentage} {time}"

[[block]]
interval = 1
block = "memory"
display_type = "memory"
format_mem = "{mem_used} /{mem_total}"
format_swap = "{swap_used} /{swap_total}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {barchart} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{min}C"
chip = "k10temp-*"
inputs = ["Tdie"]

[[block]]
block = "sound"
step_width = 5
on_click = "pavucontrol"
show_volume_when_muted = true

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 1
format = "%F %a %T"
