[window]
startup_mode = "Maximized"

[font]
normal = {family = "Liberation Mono"}
bold = {family = "Liberation Mono"}
italic = {family = "Liberation Mono"}
bold_italic = {family = "Liberation Mono"}
size = 9.0


[colors]
draw_bold_text_with_bright_colors = true

# XTerm's default colors
[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.normal]
black =   "0x000000"
red =     "0xcd0000"
green =   "0x00cd00"
yellow =  "0xcdcd00"
blue =    "0x6395ec"
magenta = "0xcd00cd"
cyan =    "0x00cdcd"
white =   "0xe5e5e5"

[colors.bright]
black =   "0x7f7f7f"
red =     "0xff0000"
green =   "0x00ff00"
yellow =  "0xffff00"
blue =    "0x3345ff"
magenta = "0xff00ff"
cyan =    "0x00ffff"
white =   "0xffffff"

[mouse]
hide_when_typing = true
